// Generated by gencpp from file rss2_msgsrv_pkg/turtlebot_move_square.msg
// DO NOT EDIT!


#ifndef RSS2_MSGSRV_PKG_MESSAGE_TURTLEBOT_MOVE_SQUARE_H
#define RSS2_MSGSRV_PKG_MESSAGE_TURTLEBOT_MOVE_SQUARE_H

#include <ros/service_traits.h>


#include <rss2_msgsrv_pkg/turtlebot_move_squareRequest.h>
#include <rss2_msgsrv_pkg/turtlebot_move_squareResponse.h>


namespace rss2_msgsrv_pkg
{

struct turtlebot_move_square
{

typedef turtlebot_move_squareRequest Request;
typedef turtlebot_move_squareResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct turtlebot_move_square
} // namespace rss2_msgsrv_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rss2_msgsrv_pkg::turtlebot_move_square > {
  static const char* value()
  {
    return "774421ec0e986291577c56de248181db";
  }

  static const char* value(const ::rss2_msgsrv_pkg::turtlebot_move_square&) { return value(); }
};

template<>
struct DataType< ::rss2_msgsrv_pkg::turtlebot_move_square > {
  static const char* value()
  {
    return "rss2_msgsrv_pkg/turtlebot_move_square";
  }

  static const char* value(const ::rss2_msgsrv_pkg::turtlebot_move_square&) { return value(); }
};


// service_traits::MD5Sum< ::rss2_msgsrv_pkg::turtlebot_move_squareRequest> should match
// service_traits::MD5Sum< ::rss2_msgsrv_pkg::turtlebot_move_square >
template<>
struct MD5Sum< ::rss2_msgsrv_pkg::turtlebot_move_squareRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rss2_msgsrv_pkg::turtlebot_move_square >::value();
  }
  static const char* value(const ::rss2_msgsrv_pkg::turtlebot_move_squareRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rss2_msgsrv_pkg::turtlebot_move_squareRequest> should match
// service_traits::DataType< ::rss2_msgsrv_pkg::turtlebot_move_square >
template<>
struct DataType< ::rss2_msgsrv_pkg::turtlebot_move_squareRequest>
{
  static const char* value()
  {
    return DataType< ::rss2_msgsrv_pkg::turtlebot_move_square >::value();
  }
  static const char* value(const ::rss2_msgsrv_pkg::turtlebot_move_squareRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse> should match
// service_traits::MD5Sum< ::rss2_msgsrv_pkg::turtlebot_move_square >
template<>
struct MD5Sum< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rss2_msgsrv_pkg::turtlebot_move_square >::value();
  }
  static const char* value(const ::rss2_msgsrv_pkg::turtlebot_move_squareResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse> should match
// service_traits::DataType< ::rss2_msgsrv_pkg::turtlebot_move_square >
template<>
struct DataType< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse>
{
  static const char* value()
  {
    return DataType< ::rss2_msgsrv_pkg::turtlebot_move_square >::value();
  }
  static const char* value(const ::rss2_msgsrv_pkg::turtlebot_move_squareResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSS2_MSGSRV_PKG_MESSAGE_TURTLEBOT_MOVE_SQUARE_H
