// Generated by gencpp from file rss2_msgsrv_pkg/turtlebot_move_squareResponse.msg
// DO NOT EDIT!


#ifndef RSS2_MSGSRV_PKG_MESSAGE_TURTLEBOT_MOVE_SQUARERESPONSE_H
#define RSS2_MSGSRV_PKG_MESSAGE_TURTLEBOT_MOVE_SQUARERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rss2_msgsrv_pkg
{
template <class ContainerAllocator>
struct turtlebot_move_squareResponse_
{
  typedef turtlebot_move_squareResponse_<ContainerAllocator> Type;

  turtlebot_move_squareResponse_()
    : success(false)  {
    }
  turtlebot_move_squareResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> const> ConstPtr;

}; // struct turtlebot_move_squareResponse_

typedef ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<std::allocator<void> > turtlebot_move_squareResponse;

typedef boost::shared_ptr< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse > turtlebot_move_squareResponsePtr;
typedef boost::shared_ptr< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse const> turtlebot_move_squareResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator1> & lhs, const ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator1> & lhs, const ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rss2_msgsrv_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rss2_msgsrv_pkg/turtlebot_move_squareResponse";
  }

  static const char* value(const ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turtlebot_move_squareResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rss2_msgsrv_pkg::turtlebot_move_squareResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSS2_MSGSRV_PKG_MESSAGE_TURTLEBOT_MOVE_SQUARERESPONSE_H
