(cl:defpackage rss2_msgsrv_pkg-srv
  (:use )
  (:export
   "SRV_TURTLEBOT_MOVE"
   "<SRV_TURTLEBOT_MOVE-REQUEST>"
   "SRV_TURTLEBOT_MOVE-REQUEST"
   "<SRV_TURTLEBOT_MOVE-RESPONSE>"
   "SRV_TURTLEBOT_MOVE-RESPONSE"
   "TURTLEBOT_MOVE_SQUARE"
   "<TURTLEBOT_MOVE_SQUARE-REQUEST>"
   "TURTLEBOT_MOVE_SQUARE-REQUEST"
   "<TURTLEBOT_MOVE_SQUARE-RESPONSE>"
   "TURTLEBOT_MOVE_SQUARE-RESPONSE"
  ))

